fixedDelay: 5000
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: contract
          producer:
            requiredGroups : contractor
      rabbit:
        bindings:
          producer:
            exchangeType: direct